data:
    dataset: "Xray"
    image_size: 64
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: False #True
    rescaled: true
    num_workers: 4
    subset_1k: True #Amodif
    out_of_dist: False

model:
    type: "openai"
    in_channels: 3
    out_channels: 3
    num_channels: 128
    num_heads: 4
    num_res_blocks: 3
    attention_resolutions: "16, 8"
    dropout: 0.0
    resamp_with_conv: True
    learn_sigma: False #Acheck
    use_scale_shift_norm: True
    use_fp16: true
    resblock_updown: False
    num_heads_upsample: 4
    var_type: 'fixedsmall'
    num_head_channels: 64
    image_size: 64
    class_cond: false
    use_new_attention_order: false

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    batch_size: 8
    last_only: True
